stages:
  - build
  - test

image: gcc

build-job:
  stage: build
  before_script:
    - apt update && apt -y install asciidoctor
  script:
    - make
  artifacts:
    paths:
      - test_microtoml
      - "*.o"

test-job:
  stage: test
  script:
    - make test
