stages:
  - build
  - test

ubuntu-gcc:
  image: ubuntu:latest
  stage: build
  before_script:
    - apt update && apt -y install gcc make asciidoctor
  script:
    - make
  artifacts:
    paths:
      - test_microtoml

ubuntu-clang:
  image: ubuntu:20.04
  stage: build
  before_script:
    - apt update && apt -y install clang make asciidoctor
  script:
    - env CC=clang make
  artifacts:
    paths:
      - test_microtoml

test-clang:
  image: debian:latest
  stage: test
  script:
    - ./test_microtoml
  dependencies:
    - ubuntu-clang

test-gcc:
  image: ubuntu:latest
  stage: test
  script:
    - ./test_microtoml
  dependencies:
    - ubuntu-gcc
