# SX130x digital baseband signal processing engine
type = "SPI"
device = "/dev/spidev0.0"
lorawan_public = true
clksrc = 0
antenna_gain = 0 # in dBi
full_duplex = false
fine_timestamp_enable = false
fine_timestamp_mode = "all_sf" # high_capacity or all_sf

[radio_0]
enable = true
type = "SX1250"
freq = 917200000
rssi_offset = -215.4
rssi_tcomp_coeff_a = 0
rssi_tcomp_coeff_b = 0
rssi_tcomp_coeff_c = 20.41
rssi_tcomp_coeff_d = 2162.56
rssi_tcomp_coeff_e = 0
tx_enable = true
tx_freq_min = 915000000
tx_freq_max = 928000000
tx_gain_lut = [ { rf_power = 12, pa_gain = 1, pwr_idx = 6 },
	      	{ rf_power = 13, pa_gain = 1, pwr_idx = 7 },
		{ rf_power = 14, pa_gain = 1, pwr_idx = 8 },
		{ rf_power = 15, pa_gain = 1, pwr_idx = 9 },
		{ rf_power = 16, pa_gain = 1, pwr_idx = 10 },
		{ rf_power = 17, pa_gain = 1, pwr_idx = 11 },
		{ rf_power = 18, pa_gain = 1, pwr_idx = 12 },
		{ rf_power = 19, pa_gain = 1, pwr_idx = 13 },
		{ rf_power = 20, pa_gain = 1, pwr_idx = 14 },
		{ rf_power = 21, pa_gain = 1, pwr_idx = 15 },
		{ rf_power = 22, pa_gain = 1, pwr_idx = 16 },
		{ rf_power = 23, pa_gain = 1, pwr_idx = 17 },
		{ rf_power = 24, pa_gain = 1, pwr_idx = 18 },
		{ rf_power = 25, pa_gain = 1, pwr_idx = 19 },
		{ rf_power = 26, pa_gain = 1, pwr_idx = 21 },
	      	{ rf_power = 27, pa_gain = 1, pwr_idx = 22 } ]

[radio_1]
enable = true
type = "SX1250"
freq = 917900000
rssi_offset = -215.4
rssi_tcomp_coeff_a = 0
rssi_tcomp_coeff_b = 0
rssi_tcomp_coeff_c = 20.41
rssi_tcomp_coeff_d = 2162.56
rssi_tcomp_coeff_e = 0
tx_enable = false

[multiSF_IF0] # Freq : 916.8 MHz
enable = true
radio = 0
if = -400000

[multiSF_IF1] # Freq : 917.0 MHz
enable = true
radio = 0
if = -200000

[multiSF_IF2] # Freq : 917.2 MHz
enable = true
radio = 0
if = 0

[multiSF_IF3] # Freq : 917.4 MHz
enable = true
radio = 0
if = 200000

[multiSF_IF4] # Freq : 917.6 MHz
enable = true
radio = 1
if = -300000

[multiSF_IF5] # Freq : 917.8 MHz
enable = true
radio = 1
if = -100000

[multiSF_IF6] # Freq : 918.0 MHz
enable = true
radio = 1
if = 100000

[multiSF_IF7] # Freq : 918.2 MHz
enable = true
radio = 1
if = 300000

[LoRa_IF8] # Freq : 917.5 MHz
enable = true
radio = 0
if = 300000
bandwidth = 500000
spread_factor = 8
implicit_hdr = false
implicit_payload_length = 17
implicit_crc_en = false
implicit_coderate = 1
